### ISSUE TITLE
Conflicting packages 

### ISSUE THREAD

**Issue by arifje** [jrrdnx/craft-ip-restrictor#2]
```
 Problem 1
    - jrrdnx/craft-ip-restrictor[1.1.0, ..., 1.1.2] require dxw/cidr ^3.0.0 -> satisfiable by dxw/cidr[v3.0.0, ..., v3.2.0].
    - dxw/cidr[v3.0.0, ..., v3.2.0] require phpseclib/phpseclib ^2.0 -> found phpseclib/phpseclib[2.0.0, ..., 2.0.x-dev] but these were not loaded, likely because it conflicts with another require.
    - dxw/cidr[v3.1.1, ..., v3.1.2] require php ^7.2 -> your php version (8.1; overridden via config.platform, actual: 8.1.27) does not satisfy that requirement.
    - Root composer.json requires jrrdnx/craft-ip-restrictor ^1.1 -> satisfiable by jrrdnx/craft-ip-restrictor[1.1.0, 1.1.1, 1.1.2].
   ```

Probably due to restricted version of dxw/cidr (3.2.0 supports php 8.1, but older versions not)

**Comment by jrrdnx** [comment]
Can you post your current composer.json?

**Comment by arifje** [comment]
Already solved it by updating some other packages, thanks!

EDIT: btw, I thought this plugin also worked as a blacklist for specific ip's, but that's not the case. Would be a good feature though :-)

**Comment by jrrdnx** [comment]
Good to hear. Blacklist is a great idea, I'll definitely look into adding that feature! https://github.com/jrrdnx/craft-ip-restrictor/issues/5
