### ISSUE TITLE
Restrict CP access only for some usergroups 

### ISSUE THREAD

**Issue by keiichikatsura** [jrrdnx/craft-ip-restrictor#7]
It would be very nice if this plugin can restrict CP access only for some usergroups.

**Comment by jrrdnx** [comment]
Knowing what user group(s) the user belongs to would require them to be logged in first, which means you'd need to allow access from all IP addresses. And at that point you can use the permissions for that user/group to block access to the CP.

Let me know if that makes sense or if I'm misunderstanding.

**Comment by keiichikatsura** [comment]
Yes, I think that method is very fine.
